[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
live_config_reload = true

[font]
size = 11

[font.normal]
family = "Ubuntu Sans Mono"
style = "Medium"

[window]
decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 300
blink_timeout = 0
thickness = 0.2

[colors.cursor]
text = "CellBackground"
cursor = "#4dffff"

[mouse]
hide_when_typing = true
