# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    #
    # Boot Configuration
    #
    boot = {
        initrd = {
            availableKernelModules = [
                "nvme"
                "xhci_pci"
                "usb_storage"
                "sd_mod"
            ];
            kernelModules = [ ];
        };
        kernelModules = [ "kvm-amd" ];
        extraModulePackages = [ ];
    };

    #
    # File Systems
    #
    fileSystems = {
        "/" = {
            device = "/dev/disk/by-uuid/c7dff420-5885-4964-bf3c-0b554267128b";
            fsType = "ext4";
        };
        "/boot" = {
            device = "/dev/disk/by-uuid/78C4-BA30";
            fsType = "vfat";
            options = [ "fmask=0077" "dmask=0077" ];
        };
    };

    swapDevices = [ ];

    #
    # Network Configuration
    #
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

    #
    # System Configuration
    #
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
